In [1]:
import pandas

In [2]:
db = pandas.read_csv('Book1.csv')

In [3]:
db

name   hrs  marks
0  ayush     5     50
1     ani    6     60
2   vimal    7     70
3     abs    8     80

In [4]:
y = db["marks"]

In [5]:
y

0    50
1    60
2    70
3    80
Name: marks, dtype: int64

In [6]:
x = db["hrs"]

In [7]:
x

0    5
1    6
2    7
3    8
Name: hrs, dtype: int64

In [8]:
x = x.values

In [9]:
type(x)

numpy.ndarray

In [10]:
x = x.reshape(4,1)

In [11]:
x

array([[5],
       [6],
       [7],
       [8]], dtype=int64)

In [12]:
type(x)

numpy.ndarray

In [13]:
x.shape

(4, 1)

In [14]:
from sklearn.linear_model import LinearRegression

In [15]:
mind = LinearRegression()

In [16]:
mind.fit(x,y)

LinearRegression()

In [17]:
mind.predict([[7]])

array([70.])

In [18]:
mind.coef_


array([10.])

In [19]:
import joblib

In [21]:
joblib.dump(mind,'marks.pk1')

['marks.pk1']